version: '3.9'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: 'highload-test'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
    command: ['postgres', '-c', 'max_connections=600', '-c', 'log_statement=ddl']
    ports:
      - '5432:5432'
    volumes:
      - strapi-data:/var/lib/postgresql/data

volumes:
  strapi-data:
